### ISSUE TITLE
Sending tokens using Accros protocol onto Boba Network shows the routing as: OMG Network: Boba Gateway on Etherscan 

### ISSUE THREAD

**Issue by DaRealX** [across-protocol/relayer-v2#234]
Not sure where to post this but here it is. :-)

Sending tokens using Accros protocol onto Boba Network shows the routing as: OMG Network: Boba Gateway on Etherscan.
Have a look at this transaction for example, hoover over the 2nd tx from the bottom (See attachment).

https://etherscan.io/tx/0x23ee18ffeece4976b5c57435aaf8ad54f83512a7525fc0f4d66f690f0131a0e5

It shouldn't mention OMG Network, and Boba Gateway should be Boba Network.

Kind regards,
A
![Transaction from Across protocol to OMG Network Boba Gateway 28-07-2022](https://user-images.githubusercontent.com/80894290/181497277-db5d2600-96a3-432c-9981-12a1933d9e98.png)

**Comment by mrice32** [comment]
Hey @DaRealX, thanks for opening this issue!

What you're seeing is an Etherscan label for the Boba Gateway. Across doesn't control these labels.

You can request that Etherscan update the name [here](https://etherscan.io/contactus?id=9).

Sorry we can't do more to help!
